sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
gemfile:
  - Gemfile
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - gem install bundler -v 1.15.4

before_script: "bundle update"

script: "bundle exec rake test"
